#!/bin/bash
# Debezium Setup Script
# Downloads the Debezium MySQL connector plugin, generates connect config,
# starts Kafka Connect, then registers the MySQL connector.
# Requires Kafka to already be running (run kafka-setup/install.sh first).

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGINS_DIR="$SCRIPT_DIR/plugins"
PROPS_FILE="$SCRIPT_DIR/connect-distributed.properties"
CONNECTOR_JSON="$SCRIPT_DIR/mysql-connector.json"
PID_FILE="$SCRIPT_DIR/debezium.pid"
LOG_FILE="$SCRIPT_DIR/debezium.log"

DEBEZIUM_VERSION="2.4.0.Final"
PLUGIN_URL="https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/${DEBEZIUM_VERSION}/debezium-connector-mysql-${DEBEZIUM_VERSION}-plugin.tar.gz"

echo "=== Debezium Setup ==="

# -----------------------------------------
# 0. Java 17 (same requirement as Kafka)
# -----------------------------------------
JAVA17_HOME="$(brew --prefix openjdk@17 2>/dev/null)"
if [ -x "$JAVA17_HOME/bin/java" ]; then
    export JAVA_HOME="$JAVA17_HOME"
    export PATH="$JAVA_HOME/bin:$PATH"
else
    echo "ERROR: openjdk@17 not found. Run: brew install openjdk@17"
    exit 1
fi

# -----------------------------------------
# 1. Check Kafka Connect binary is available
# -----------------------------------------
if ! command -v connect-distributed &>/dev/null; then
    echo "ERROR: Kafka not installed. Run kafka-setup/install.sh first."
    exit 1
fi

# -----------------------------------------
# 1b. Check Kafka broker is reachable
# -----------------------------------------
if ! kafka-topics --bootstrap-server localhost:9092 --list &>/dev/null; then
    echo "ERROR: Kafka broker is not reachable on localhost:9092."
    echo "Start it first: cd ../kafka-setup && ./install.sh"
    exit 1
fi
echo "Kafka broker is reachable."

# -----------------------------------------
# 2. Download Debezium MySQL connector plugin
# -----------------------------------------
if [ ! -d "$PLUGINS_DIR" ]; then
    echo "Downloading Debezium MySQL connector ${DEBEZIUM_VERSION}..."
    mkdir -p "$PLUGINS_DIR"
    ARCHIVE="$SCRIPT_DIR/debezium-connector-mysql.tar.gz"
    curl -L "$PLUGIN_URL" -o "$ARCHIVE"
    tar -xzf "$ARCHIVE" -C "$PLUGINS_DIR"
    rm -f "$ARCHIVE"
    echo "Plugin downloaded."
else
    echo "Debezium plugin already present."
fi

# -----------------------------------------
# 3. Generate connect-distributed.properties
# -----------------------------------------
cat > "$PROPS_FILE" << EOF
# Auto-generated by install.sh
bootstrap.servers=localhost:9092
group.id=debezium-connect-group

plugin.path=$PLUGINS_DIR

config.storage.topic=debezium-configs
config.storage.replication.factor=1
config.storage.partitions=1

offset.storage.topic=debezium-offsets
offset.storage.replication.factor=1
offset.storage.partitions=1
offset.flush.interval.ms=10000

status.storage.topic=debezium-status
status.storage.replication.factor=1
status.storage.partitions=1

key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

rest.host.name=localhost
rest.port=8083
EOF

# -----------------------------------------
# 4. Start Kafka Connect (skip if running)
# -----------------------------------------
if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    echo "Kafka Connect is already running (PID $(cat "$PID_FILE"))."
else
    echo "Starting Kafka Connect..."
    nohup connect-distributed "$PROPS_FILE" > "$LOG_FILE" 2>&1 &
    echo $! > "$PID_FILE"

    echo -n "Waiting for Kafka Connect REST API"
    for i in $(seq 1 30); do
        sleep 2
        if curl -sf http://localhost:8083/ &>/dev/null; then
            echo " ready."
            break
        fi
        echo -n "."
        if [ "$i" -eq 30 ]; then
            echo ""
            echo "ERROR: Kafka Connect did not start within 60 seconds."
            echo "Check logs: $LOG_FILE"
            exit 1
        fi
    done
fi

# -----------------------------------------
# 5. Register MySQL connector
# -----------------------------------------
EXISTING=$(curl -sf http://localhost:8083/connectors/mysql-inventory-connector 2>/dev/null || true)
if [ -n "$EXISTING" ]; then
    echo "Connector already registered. Updating..."
    curl -sf -X PUT http://localhost:8083/connectors/mysql-inventory-connector/config \
        -H "Content-Type: application/json" \
        -d "$(cat "$CONNECTOR_JSON" | python3 -c 'import sys,json; d=json.load(sys.stdin); print(json.dumps(d["config"]))')" \
        | python3 -m json.tool
else
    echo "Registering MySQL connector..."
    curl -sf -X POST http://localhost:8083/connectors \
        -H "Content-Type: application/json" \
        -d @"$CONNECTOR_JSON" \
        | python3 -m json.tool
fi

echo ""
echo "=== Setup Complete ==="
echo "  Kafka Connect REST : http://localhost:8083"
echo "  Connectors         : http://localhost:8083/connectors"
echo "  Logs               : $LOG_FILE"
echo "  PID                : $(cat "$PID_FILE")"
