#!/bin/bash
# Kafka Setup Script (KRaft mode — no Zookeeper)
# Installs Kafka via Homebrew (if missing), generates server.properties,
# formats storage on first run, then starts the broker.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="$SCRIPT_DIR/kafka-logs"
SERVER_PROPS="$SCRIPT_DIR/server.properties"
PID_FILE="$SCRIPT_DIR/kafka.pid"
LOG_FILE="$SCRIPT_DIR/kafka.log"

echo "=== Kafka Setup ==="

# -----------------------------------------
# 0. Ensure Java 17+ is used (Kafka requires it)
# -----------------------------------------
JAVA17="$(brew --prefix openjdk@17 2>/dev/null)/bin/java"
if [ -x "$JAVA17" ]; then
    export JAVA_HOME="$(brew --prefix openjdk@17)"
    export PATH="$JAVA_HOME/bin:$PATH"
    echo "Using Java: $($JAVA17 -version 2>&1 | head -1)"
else
    echo "Java 17 not found, installing..."
    brew install openjdk@17
    export JAVA_HOME="$(brew --prefix openjdk@17)"
    export PATH="$JAVA_HOME/bin:$PATH"
fi

# -----------------------------------------
# 1. Install via Homebrew if not present
# -----------------------------------------
if ! command -v kafka-server-start &>/dev/null; then
    echo "Installing Kafka via Homebrew..."
    brew install kafka
    echo "Kafka installed."
else
    echo "Kafka already installed."
fi

# -----------------------------------------
# 2. Generate server.properties
# -----------------------------------------
cat > "$SERVER_PROPS" << EOF
# Auto-generated by install.sh — edit install.sh to change settings
process.roles=broker,controller
node.id=1
controller.quorum.voters=1@localhost:9093
listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
advertised.listeners=PLAINTEXT://localhost:9092
controller.listener.names=CONTROLLER
inter.broker.listener.name=PLAINTEXT
log.dirs=$LOG_DIR
num.partitions=1
default.replication.factor=1
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
log.retention.hours=168
auto.create.topics.enable=true
group.initial.rebalance.delay.ms=0
EOF

# -----------------------------------------
# 3. Format KRaft storage on first run
# -----------------------------------------
if [ ! -f "$LOG_DIR/meta.properties" ]; then
    echo "Formatting Kafka storage (KRaft)..."
    mkdir -p "$LOG_DIR"
    CLUSTER_UUID=$(kafka-storage random-uuid)
    kafka-storage format -t "$CLUSTER_UUID" -c "$SERVER_PROPS"
    echo "Storage formatted (cluster ID: $CLUSTER_UUID)."
fi

# -----------------------------------------
# 4. Start broker (skip if already running)
# -----------------------------------------
if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    echo "Kafka is already running (PID $(cat "$PID_FILE"))."
    exit 0
fi

echo "Starting Kafka..."
nohup env JAVA_HOME="$JAVA_HOME" PATH="$JAVA_HOME/bin:$PATH" kafka-server-start "$SERVER_PROPS" > "$LOG_FILE" 2>&1 &
echo $! > "$PID_FILE"

echo -n "Waiting for Kafka to be ready"
for i in $(seq 1 30); do
    sleep 1
    if kafka-topics --bootstrap-server localhost:9092 --list &>/dev/null; then
        echo " ready."
        break
    fi
    echo -n "."
    if [ "$i" -eq 30 ]; then
        echo ""
        echo "ERROR: Kafka did not start within 30 seconds."
        echo "Check logs: $LOG_FILE"
        exit 1
    fi
done

echo ""
echo "=== Setup Complete ==="
echo "  Broker : localhost:9092"
echo "  Logs   : $LOG_FILE"
echo "  PID    : $(cat "$PID_FILE")"
